<a href="https://colab.research.google.com/github/Lehazirov/dap-2024/blob/main/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy
# Задание
Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024.
5. Название pull request должно иметь формат "<Номер лабораторной работы> <Номер группы> <ФИО>"
6. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

## 1. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [2]:
import numpy as np
array = np.random.randint(1, 100, (10, 10))
print("Созданный массив:\n", array)
min_value = array.min()
max_value = array.max()
print("\nМинимальное значение массива:", min_value)
print("Максимальное значение массива:", max_value)

Созданный массив:
 [[96 71 26 76 45 52  5 38 71 10]
 [66 47 26 28 44 42 34 48 81 48]
 [41 49 53 66 43 13 86 62 98 23]
 [61 38 39 78 30 17  8 13 73 56]
 [48 44 81 10 43 15 48 76  6 50]
 [50 56 24 19 19 36 88 94  4  7]
 [53 54 34 52 94 21  8  2 84  8]
 [71 95 33 51 12 10 88  8 81 44]
 [53 90 90 59 87 80 97 60 33 84]
 [ 6 86 25 87 44 29 15 84 25 53]]

Минимальное значение массива: 2
Максимальное значение массива: 98


## 2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
import numpy as np
matrix = np.zeros((8, 8))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print("Матрица в шахматном порядке:\n", matrix)

Матрица в шахматном порядке:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
import numpy as np
z = np.arange(11)
print("Исходный массив:\n", z)
z[(z > 3) & (z < 8)] *= -1
print("Результат:\n", z)


Исходный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10]
Результат:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## 4. Найти среднее значение строки матрицы и вычесть его из каждого элемента строки


In [5]:
import numpy as np
z = np.random.rand(5, 10)
print("Исходная матрица:\n", z)
means = np.mean(z, axis=1, keepdims=True)
z -= means
print("\nСредние значения строк:\n", means.flatten())
print("\nРезультат:\n", z)


Исходная матрица:
 [[0.54821529 0.81187733 0.9451326  0.56490687 0.53999051 0.65485413
  0.98512894 0.16701036 0.57035013 0.19115218]
 [0.3256708  0.95832567 0.54065842 0.03840587 0.23793715 0.1800465
  0.84477375 0.10758256 0.2025184  0.31576778]
 [0.57472089 0.34988652 0.69083897 0.10860215 0.16863844 0.03055213
  0.3093481  0.3726248  0.48282539 0.06697855]
 [0.49625662 0.27438261 0.41274533 0.29407505 0.31876592 0.79337075
  0.66692024 0.56521705 0.90001081 0.19844796]
 [0.14541112 0.97800757 0.49119451 0.3815938  0.29498658 0.63951397
  0.29117225 0.07648742 0.74673102 0.6603806 ]]

Средние значения строк:
 [0.59786183 0.37516869 0.3155016  0.49201923 0.47054788]

Результат:
 [[-0.04964654  0.21401549  0.34727077 -0.03295496 -0.05787132  0.0569923
   0.38726711 -0.43085148 -0.0275117  -0.40670965]
 [-0.04949789  0.58315698  0.16548973 -0.33676282 -0.13723154 -0.19512219
   0.46960506 -0.26758613 -0.17265029 -0.05940091]
 [ 0.25921929  0.03438493  0.37533738 -0.20689944 -0.14686315

## 5. Поменять 1 и 2 строки матрицы


In [6]:
import numpy as np
z = np.arange(25).reshape(5, 5)
print("Исходная матрица:\n", z)
z[[0, 1]] = z[[1, 0]]
print("\nРезультат после замены строк:\n", z)


Исходная матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Результат после замены строк:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную


In [7]:
import numpy as np
z = np.random.random((10, 2))
print("Исходный массив точек:\n", z)
r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)
theta = np.arctan2(z[:, 1], z[:, 0])
print("\nРадиусы (r):\n", r)
print("\nУглы (theta):\n", theta)


Исходный массив точек:
 [[0.05634967 0.80068542]
 [0.82441517 0.02637187]
 [0.93403693 0.20210772]
 [0.10064135 0.19041959]
 [0.22372309 0.69571495]
 [0.01725901 0.49196475]
 [0.26142405 0.95006701]
 [0.88992934 0.55755156]
 [0.69836857 0.48761944]
 [0.30744176 0.95532366]]

Радиусы (r):
 [0.80266582 0.82483686 0.95565293 0.21537944 0.73080183 0.49226739
 0.98537802 1.05016092 0.85175781 1.00357548]

Углы (theta):
 [1.50053538 0.03197767 0.21309564 1.08459065 1.25966722 1.5357289
 1.30227784 0.55968598 0.6095347  1.25944379]


## 7. Заменить максимальный элемент массива на ноль


In [8]:
import numpy as np
z = np.random.random(10)
print("Исходный массив:\n", z)
z[z.argmax()] = 0
print("\nРезультат:\n", z)


Исходный массив:
 [0.92260692 0.36666481 0.59449268 0.38466312 0.60163469 0.17101083
 0.89822398 0.1441706  0.55754396 0.97485567]

Результат:
 [0.92260692 0.36666481 0.59449268 0.38466312 0.60163469 0.17101083
 0.89822398 0.1441706  0.55754396 0.        ]


## 8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз


In [9]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
np.add.at(z, i, 1)
print("Результат:\n", z)


Результат:
 [1. 2. 6. 1. 4. 3. 3. 3. 5. 2.]


## 9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением


In [10]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])
print("Исходный вектор:\n", z)
z_new = np.zeros(len(z) * 4 - 3)
z_new[::4] = z
print("\nРезультат:\n", z_new)


Исходный вектор:
 [1 2 3 4 5]

Результат:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 10. Найти ближайшее к заданному значению число в заданном массиве


In [11]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0, 100)
print("Заданный массив:\n", z)
print("\nЗаданное число:\n", v)
closest = z[np.abs(z - v).argmin()]
print("\nБлижайшее число:\n", closest)


Заданный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Заданное число:
 64.10309252711936

Ближайшее число:
 64


# Вопросы
1. Какой тип (dtype) будут иметь элементы массива?

np.array([1, 4, 2, 5, 3])   
np.array([1., 4, 2, 5, 3])   
np.array([1, 4, 2, 5, 3], dtype='float128')   
np.array([1., 4, 2, 5, 3], dtype='complex128')   
np.array([1, 4, 2, 5, 3], dtype ='float64')   
np.array([1, 4, 2, 5, 3], dtype =int64)   
np.array([1, 4, 2, 5, 3], dtype='bool')   
np.array([1, 4, 2, 5, 3], dtype='str')   
np.array([1, 4, 2, 5, '3'])   
np.array([1, -4, 2, 0, 1j])   
2. Что будет выведено в консоль и почему?

np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'   
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]   
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]   
np.array([1, -4, 2, 0, True], dtype='int64')[-1]   
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]   
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]   
np.array([1, 4, 2, 5, '3'])[-1] * 3   
3. Каков результат операции?

np.ones((3, 5), dtype=float)   
np.full((3, 5), 3.14)   
np.linspace(0, 1, 5)   
np.diag((1,3,5))   
np.smile((1,3,5))   
np.random.random((3, 3))   
np.eye(3)   
np.empty(3)   
4. Дан двумерный массив X, что будет выведено в консоль?

X = np.array([[3, 5, 2, 4],   
      [7, 6, 8, 8],   
      [1, 6, 7, 7]])   

X[0,0]   
X[-1,-1]   
X[0:1,-1]   
X[0:2,-1]   
X[0:2,0:2]   
X[1,1:3]   
X[1,:]   
X[1,:]   
X[:,:]   
X[:]   
X[::2,::2]   
X[0:3:2,0:3:2]   
X[::-1,::-1]   
5. Дан двумерный массив grid, в чем различее между операциями?

grid = np.arange(16).reshape((4, 4))   
np.split(grid, [2])   
np.split(grid, [2], axis=1)   
6. В чем различие между операциями?

[1, 2, 3] + [3, 2, 1]   
    np.array([1, 2, 3]) + np.array([3, 2, 1])   
7. Как в CodeLab измерить время выполнения кода?

8. Дан массив X, каковы результаты операций?

X = np.array([[3, 5, 2, 4],   
      [7, 6, 8, 8],   
      [1, 6, 7, 7]])   

np.sum(M)   
np.sum(M, axis=1)   
np.sum(M, axis=0)   
np.sum(M, axis=2)   
np.sum(M, 1)   
sum(M)   
sum(M,1)   
9. Дан массив X, что будет выведено в консоль?

X = np.array([1,2,3,4])   

X > 3   
X < 3   
X[X < 3]   
X[X > 3]   
X[X != 3]   
10. В чем преимущество массивов NumPy по сравнению с обычными списками. Чем обусловлено это преимущество?